### ISSUE TITLE
Обсуждение и доработки проекта

### ISSUE THREAD

**Issue by zigithu** [pinya/kuhomon#10]
Бесплатный blynk сервер предоставляет 2000 энергии. Я настроил blynk для этого проекта использовав 1700 энергии. Этого хватит для того чтобы ознакомиться с возможностями этого проекта без разворачивания своего собственного блинк сервера. 
PS я собрал проект состоящий из одного датчика CO2 и одного датчика bme280. 
пины для блинка:
V1- температура
V2 - влажность
V4 - давление
V5 - СО2
![clone_1](https://user-images.githubusercontent.com/26819289/27005804-f308a170-4e2e-11e7-89bf-8ad46275804b.png)
![screenshot__cc blynk2](https://user-images.githubusercontent.com/26819289/27005805-f6a05800-4e2e-11e7-9b11-e9b72ff89242.png)

**Comment by zigithu** [comment]
У меня вопрос к автору: зачем в предлагаемом вот здесь https://geektimes.ru/post/284994/ проекте блинка присутствует кнопка FW update.
Я так понимаю это обновление прошивки по воздуху. Зачем оно надо? и откуда оно прилетает... что-то в коде не смог найти этот момент.

**Comment by kumekay** [comment]
Перенес Blynk приложение в вики https://github.com/pinya/kuhomon/wiki/Blynk-application-QR-code

FW update позволяет загружать новую прошивку с указанного http адреса. В коде https://github.com/pinya/kuhomon/blob/master/src/main.cpp#L387-L411

Обсуждения давайте вести в Gitter-e https://gitter.im/kuhomon/Lobby#
