### ISSUE TITLE
Проверенные комплектующие и магазины

### ISSUE THREAD

**Issue by zigithu** [pinya/kuhomon#11]
1) **NodeMcu**
В них установлена более медленная флеш память не QUAD а DIO (пруф https://github.com/karawin/Ka-Radio/issues/13)
Как оказалось это не оригинальный AI-Thinker а клон (HYSIRY).
На данных платах на пине VIN нет 5В. Для запитки датчика CO2 я использовал пин VU (слева третий сверху).
![hysiry2](https://user-images.githubusercontent.com/26819289/27006103-dc787416-4e34-11e7-837d-738fda4e9038.jpg)
покупал за 3,02$ вот здесь:
https://ru.aliexpress.com/item/ESP8266-CH340G-CH340-G-NodeMcu-V3-Lua-Wireless-WIFI-Module-Connector-Development-Board-Based-ESP-12E/32800966224.html?
На Windows10 с драйверами проблем не было - поставились автоматом.
2) **Temperature/Humidity/Barometric Pressure Sensor **bme280****
![bme280](https://user-images.githubusercontent.com/26819289/27006201-b1e1a68a-4e36-11e7-84a2-edbdd16374c1.jpg)
покупал вот тут: https://ru.aliexpress.com/item/Consumer-Electronics-Shop-Free-shipping-Digital-Temperature-Humidity-Barometric-Pressure-Sensor-Module-Breakout-BME280/32601813705.html?
Покупал одну штуку за 4,89$, а продавец прислал 10 штук!!! Кто-нибудь проверьте была ли это ошибка продавца, или это норма. обязательно отпишитесь.

3) **MH-Z19 infrared co2 sensor**
![mh-z19](https://user-images.githubusercontent.com/26819289/27006204-cc7f7b84-4e36-11e7-9266-3f23fd5bcb30.jpg)
покупал за 21,18$ вот здесь
https://ru.aliexpress.com/item/MH-Z19-infrared-co2-sensor-for-co2-monitor/32535524294.html?

4) **0.96 inch OLED I2C module 128X64**
![disp](https://user-images.githubusercontent.com/26819289/27006238-9186c96e-4e37-11e7-9ef1-4f913d1e0d24.jpg)
покупал за 2,60$ вот здесь:
https://ru.aliexpress.com/item/1pcs-0-96-blue-0-96-inch-OLED-module-New-128X64-OLED-LCD-LED-Display-Module/32640627772.html?
особенность этого модуля: пины переставлены и названы по другому чем на этой схеме 
![default](https://user-images.githubusercontent.com/26819289/27006260-2224d34e-4e38-11e7-8a52-7262b413fa71.png)
GND = GND
VDD = VCC
SCK = SCL
SDA = SDA

**Comment by kumekay** [comment]
Перемещено в вики: https://github.com/pinya/kuhomon/wiki/RU-%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%82%D1%83%D1%8E%D1%89%D0%B8%D0%B5-%D0%B8-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D1%8B
