### ISSUE TITLE
Релехи

### ISSUE THREAD

**Issue by apan65** [pinya/kuhomon#12]
Можно ли добавить функцию веб-интерфейсе чтобы выставлять значения температуры\влажности при которых будут срабатывать реле. Думаю функциональность очевидна очевидна.

**Comment by apan65** [comment]
Плюс можно еще влажность и температуру на одном эране оставить. А давление неинформативно.

**Comment by kumekay** [comment]
> Можно ли добавить функцию веб-интерфейсе чтобы выставлять значения температуры\влажности при которых будут срабатывать реле. Думаю функциональность очевидна очевидна.

Это возможно сделать прямо из мобильного приложения blynk при помощи компонента Eventor без изменения прошивки:
![image](https://user-images.githubusercontent.com/2738/32701370-1f6171c4-c7d4-11e7-9d14-32154ee9b85c.png)
![image](https://user-images.githubusercontent.com/2738/32701374-31fbdd88-c7d4-11e7-8ceb-108e7677ec37.png)

**Comment by apan65** [comment]
Блин, реально, а я даже не вникал, просто графики повесил и забыл, спасибо.

**Comment by kumekay** [comment]
> Плюс можно еще влажность и температуру на одном эране оставить. А давление неинформативно.

Отображать информацию можно многими способами и универсального, подходящего для всех не существует. Возможность конфигурирования добавит ненужную сложность.
