### ISSUE TITLE
Fritzing - проблемы с компонентами

### ISSUE THREAD

**Issue by CadilVB** [pinya/kuhomon#15]
Сергей,  снова обращаюсь к вам за помощью. 
Решил нарисовать эл. схему своего макета. Мне понравился ваш стиль схемы, сделанный  в Fritzing, - наглядно и информативно. Начал искать для этой платформы новые компоненты, но безуспешно. 
Меня интересуют следующие компоненты:
WiFi NodeMCU board ESP8266 (CP2102)
MH-Z19 - датчик содержания углекислого газа
DHT22 - датчик температуры и влажности
OLED LCD 0.96 (32*128) - дисплей
Two-way 4-channel converter of logic levels 3.3-5V
RF 433MHz transmitter 
RF 433MHz  приемник
Зарегистрировался на http://forum.fritzing.org, но там процессы очень вялотекущие.
**Подскажите, пожалуйста, ссылку на новые компоненты Fritzing или поделитесь своей библиотекой.** Заранее благодарен.

**Comment by kumekay** [comment]
На самом деле fritzing я использовал только один раз - как раз для той статьи.
Пользовался в основном компонентами из https://github.com/adafruit/Fritzing-Library
https://github.com/roman-minyaylov/fritzing-parts

Компонент для mh-z19 я делал сам, но к сожалению, не могу найти его сейчас

**Comment by CadilVB** [comment]
Вы были правы - компоненты, которые не нашел в нете, оказалось проще создать самому, чем тратить время на поиски.
Успехов!
