### ISSUE TITLE
плата висит в состоянии Loading...

### ISSUE THREAD

**Issue by zigithu** [pinya/kuhomon#2]
Собрал схему только с одним датчиком (CO2 mh-z19). Загружается, по wifi доступна, на 192.168.4.1 заходит, но после конфигурирования параметров wifi плата перезагружается и висит в состоянии Loading...
В чем может быть причина? Возможно отсутствие датчиков приводит к зависанию? Возможно ли добавить проверку на отсутствие/смерть датчиков?

**Comment by kumekay** [comment]
Можете подключиться к serial консоле и прислать все, что выводится в процессе загрузки?

**Comment by zigithu** [comment]
### пока вот такие данные. Изменение кодировки не помогает
======================================

pio device monitor --port COM9 --baud **9600**
--- Miniterm on COM9  9600,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
␁␅^��␝q��

pio device monitor --port COM9 --baud **74880**
--- Miniterm on COM9  74880,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld

pio device monitor --port COM9 --baud **115200**
--- Miniterm on COM9  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
r$␀dܞ|␀�l�|␃␌␌␄�␜�l�␌#|��␃�␓��|2c�␌#�p~�o�dno���␌#␜p��bd`␃rlp�o�␐␂␌␄�␄l␄��␌␄␌B␌N�|␂l�␌␄�p␄��oN�␃$��l ␃�␓2no␌d`␃␏␃or����␂␄␌b␌�␎$␎{��N␌␄#␄�␏l�␂l���␛$�$`␃��o�␃

**Comment by kumekay** [comment]
Это нормальный вывод при загрузке, удивительно, что это все.
Отсутствие датчика CO2 и температуры/влажности не должно быть проблемой - просто будут возвращаться нули.
При отсутствии BMP в консоли должна быть строка `"Could not find a valid BMP085 sensor, check wiring!"`

Попробуйте, пожалуйста, еще раз собрать вывод консоли - не отключая плату от usb нажмите кнопку reset на плате. Вероятно там будет что-то еще
Скорость UART 115200

В начале там будет каша от загрузчика, он работает на другой скорости, но потом должен появиться вывод самой прошивки

Добавьте для проверки `DEBUG_SERIAL.println("Start init...");` после строчки `        DEBUG_SERIAL.begin(115200);` в функции setup

**Comment by zigithu** [comment]
Результат тот же. Дополнительной информации не появилось. При перезагрузке вываливает кучу мусора. При этом экран загорается и отображает стартовую станицу. Через веб то пускает то не пускает. В случае когда пускает: после указания учетных данных wifi сети подключается в точке доступа, на экране горит loading... и ничего не происходит. 
Решил пока не мучить эту плату а подожду когда приедет esp-07. Попробую на ней.

**Comment by pandability** [comment]
**zigithu**, у вас что нибудь получилось с этой или с новой платой? У меня такая же ситуация - после настройки wi-fi подключения плата висит в статусе Loading.

**Comment by pandability** [comment]
Что то внятное выдало тоже только на скорости 74880.
Если отключить или изменить параметры сети wi-fi на роутере, чтобы плата не смогла подключиться, то вывод будет отличаться boot mode:(3,7), при этом на дисплее снова увидим приглашение подключиться к плате как к AP и пройти на ip адрес для конфигурации настроек.

```
PORT OPEN 74880

Communication with MCU..Got answer! Communication with MCU established.
AutoDetect firmware...

Can't autodetect firmware, because proper answer not received (may be unknown firmware). 
Please, reset module or continue.

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld
```

**Comment by zigithu** [comment]
Заказал 2 платы на чипе 340.... жду больше месяца. Но я использовал свою NodeMCU в другом проекте и она там тоже работает очень нестабильно.
Следовательно она неисправна. но глюк плавающий - возможно надо пропаять и прогреть все контакты
PS
1)вот этот модуль глючит (v2) https://ru.aliexpress.com/item/New-Wireless-module-NodeMcu-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266-with-pcb-Antenna/32593655688.html?
2) вот эти я ожидаю https://ru.aliexpress.com/item/ESP8266-CH340G-CH340-G-NodeMcu-V3-Lua-Wireless-WIFI-Module-Connector-Development-Board-Based-ESP-12E/32800966224.html?

**Comment by kumekay** [comment]
У меня есть несколько разных модулей, попробую на этой неделе повторить такое поведение

**Comment by kumekay** [comment]
Я совсем забыл, что в опубликованной версии кода для отладочной информации испльзуется другой serial порт, и нужен был еще один usb-uart, чтобы эти данные собирать.
Я это изменил (72074ee), теперь данные выводятся в основную консоль. Я не знаю есть ли проблема, описанная в этом issue, но по крайней мере debug вывод сейчас работает.
Завтра посмотрю подробнее.

**Comment by kumekay** [comment]
Я обновил код теперь он выводит больше информации в консоль и более детально отображает статус на экране + некоторые мелкие правки, которые вероятно решили проблему, поэтому прошу попробовать последнюю версию: 02580683aca0164042c28912a3c59f0fa347836b

**Comment by zigithu** [comment]
Так, пришло время закрывать этот тикет. Мне наконец-то пришли мои платы (https://ru.aliexpress.com/item/ESP8266-CH340G-CH340-G-NodeMcu-V3-Lua-Wireless-WIFI-Module-Connector-Development-Board-Based-ESP-12E/32800966224.html?) они оказались абсолютно исправные за исключением того что судя по всему в них установлена более медленная флеш память не QUAD а DIO (вот тут можно посмотреть мой скриншот при прошивке через ESP Flash Tool https://github.com/karawin/Ka-Radio/issues/13). Как оказалось это не оригинальный AI-Thinker  а клон HYSIRY. Но тем не менее он работает. Я прошился прошивкой из ветки BME280. Как и **apan65** (https://github.com/pinya/kuhomon/issues/4) я попался на том что не указал blynk-токен. Для исправления ситуации в 421 строку вставил factoryReset(); перепрошился, потом убрал factoryReset(); и перепрошился еще раз. Датчик BME280 заработал отлично: показывает температуру влажность и атмосферное давление. А вот датчик Co2 я сжег когда перепаивал ему ноги((((( 
PS 1) логи стали очень информативные. смотрятся на скорости 115200.
2) возможно на дисплей надо вывести тоже что и в консоли? сейчас:  drawBoot("Connecting...");         DEBUG_SERIAL.println("Connecting to blynk...");
сделать:  drawBoot("Connecting to blynk ...");         DEBUG_SERIAL.println("Connecting to blynk...");
или не влезет на экран?
3) в ветке BME280 не хватает библиотеки 166 и я так понимаю ненужные библиотеки: 536,525,16
Спасибо за ваш код. Было интересно. Пойду заказывать датчик(
UPD
Как оказалось датчик CO2 абсолютно исправен! Оказалось что на данных платах NodeMcu-V3 (их у меня 2 штуки) на пине VIN напряжение 1,5В. Для запитки датчика CO2 я использовал пин VU (слева третий сверху). Теперь все отлично. 
UPD2
![myco2](https://user-images.githubusercontent.com/26819289/26915612-7fad03fc-4c2f-11e7-974c-8ed3f6354eba.PNG)

**Comment by kumekay** [comment]
Рад, что у вас все получилось!
