### ISSUE TITLE
bme-280 и датчик пыли GP2Y1014AU0F

### ISSUE THREAD

**Issue by kashaev** [pinya/kuhomon#3]
Что необходимо поменять в коде, если я буду использовать bme-280 и датчик пыли GP2Y1014AU0F.

**Comment by pinya** [comment]
А можно поподробнее в чем проблема? Кажется вы забыли добавить текст

**Comment by kumekay** [comment]
Если верить официальной схеме от sharp и вот этой инструкции, то вам еще понадобится резистор на 150 ом, и электролитический конденсатор на 220 мкФ (10в)
arduinodev.woofex.net/2012/12/01/standalone-sharp-dust-sensor

**Comment by kashaev** [comment]
Прошу прощения, что трачу Ваше время. Насчёт необходимых элементов я понял. В ближайшее время приобрету.

**Comment by kumekay** [comment]
@kashaev добрый день, как успехи с модификацией? Что-нибудь вышло?

**Comment by kumekay** [comment]
@kashaev Если вы отказались от идеи делать версию с датчиком пыли, то я закрою этот вопрос

**Comment by kashaev** [comment]
Здравствуйте! Очень много дел на работе и остается совсем мало свободного времени.. На данный момент я осваиваю азы программирования.  С 19 числа вплотную займусь этим вопросом. Все необходимые комплектующие у меня есть. Спасибо, что интересуетесь)

**Comment by kashaev** [comment]
Здравствуйте! Прошу Вашего совета. Прибор собран, датчик пыли работает исправно. Проблема заключается в том, что он крайне не чувствителен. Нужно как следует дунуть в отверстие, чтоб он показал какие - либо цифры. Не калибровал. Есть идя поставить под него или на него что-то вроде кулера для тяги. Второй вопрос по поводу CO2: датчик показывает неадекватные значения, легко сбивается. Работает нормально только после повторной прошивки, но если выключить и включить снова сбивается. Не калибровал.

**Comment by kumekay** [comment]
По поводу датчика пыли не могу сказать, т.к. никогда им не пользовался. Он у вас с вентилятором для активной продувки или без?
Датчик CO2 имеет время прогрева около 3-5 минут, соответственно после включения первое время он показывает не совсем то. Если он у вас находится в квартире с периодическим проветриванием, то калибровать его не нужно.

**Comment by kashaev** [comment]
Здравствуйте! Подскажите, пожалуйста,  можно ли самому создать приложение на ios, чтоб дублировать туда данные , приходящие на blynk? Элементарное одностраничное приложение, где будут просто показываться данные. Конструкторов приложений масса, но как их связать...

**Comment by kumekay** [comment]
Можно из скетча отправлять данные не только в blynk, но и в какой-нибудь другой сервис при помощи http запроса. Вариантов слишком много, но какой-либо в пару кликов в голову не приходит. (я никогда не интересовался конструкторами приложение)
И еще вопрос в том, чем приложение blynk не подходит

**Comment by kashaev** [comment]
Blynk подходит. Идея в том, что бы создать приложение немного с другим функционалом для группы людей, используя эти данные. Спасибо!

**Comment by kumekay** [comment]
Ок, тогда будем считать этот вопрос закрытым
