### ISSUE TITLE
BME280 в README.md 

### ISSUE THREAD

**Issue by zigithu** [pinya/kuhomon#5]
В ветке BME280 наверно в README.md 

надо это 
Humidity/Temperature SI7021 i2c. Library: https://github.com/LowPowerLab/SI7021
Pressure/Temperature BMP085 i2c. Library: https://github.com/adafruit/Adafruit-BMP085-Library

заменить вот на это
Humidity/Pressure/Temperature BME280        https://github.com/adafruit/Adafruit_BME280_Library

**Comment by kumekay** [comment]
Fixed in ee02863fa61568b8e211c38b9fcd5c51b8efa89d
