### ISSUE TITLE
Отображать все значения на одном экране

### ISSUE THREAD

**Issue by kumekay** [pinya/kuhomon#7]
Не очень удобно ждать около 10 секунд что бы увидеть все три текущих значения (T/P/H). Было бы круто увидеть все цифры на одном экране (без надобности ожидания пока обновится экран). 
К примеру значения CO2 можно переместить в левую часть экрана а в правой части разместить в колонку все три значения (T/P/H)
примерно вот так
Wifi =ok blynk=ok
567 T= 23 oC
ppm CO2 H= 48%
P=739 mmHg

**Comment by zigithu** [comment]
я имел ввиду что-то вроде этого:
![default](https://user-images.githubusercontent.com/26819289/27006007-10da5e10-4e33-11e7-8d6f-ee030eee1ff3.png)
Но лично для меня это уже не очень актуально - так как я планирую использовать датчик без дисплея.
Так же не факт что все влезет на экран. А если даже и влезет то при добавлении новых датчиков появятся новые значения которые некуда будет разместить на это экране. таким образом придется снова использовать многоэкранность.

**Comment by kumekay** [comment]
Думаю, что этот вопрос можно закрыть
